server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reconcile_db?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: ${MYSQL_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE
